name: jahardman
favicon: null
layout_spectrum: 0.657700533978641
typography_spectrum: 0.4281757140997797
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8942081527784467
  lightness: 0.14424005895853043
  saturation: 0.7862285689916462
  rhythmicContrast: 0.5498176524415612
purpose: []
